let  userModel = require("../schemas/userSchema.js");
let mongoose = require("mongoose");
require("dotenv");

async function connect(){
    await mongoose.connect(`mongodb://localhost:27017/Together`);
    dummyUserData();
}
connect()
.then(()=>{console.log("data planted sucesufull")})
.catch((err)=>{console.log("some thing went wrong in plating dummy data",err)});



async function dummyUserData(){
    for(let i=0;i<100;i++){
       let dataObj =
       {
        userName:`autoGenerated@${i}`,
        email:`autoGenerated@${i}gmail.com`,
        password:`autoGenerated@${i}`,
       };
       let data =new userModel(dataObj);
       await data.save();
    }
}
